### ISSUE TITLE
5-shot setting

### ISSUE THREAD

**Issue by King-king424** [Aldrich2y/MIANet#4]
作者您好
请问5-shot setting下 是用训练练好的1-shot model来测试 还是 重新训练一个5-shot model 来测试？

**Comment by Aldrich2y** [comment]
你好，需要重新训练一个5-shot模型。

**Comment by King-king424** [comment]
![image](https://github.com/Aldrich2y/MIANet/assets/39642013/3ac747c7-a837-4bea-84bd-e7adcc141e4d)
作者您好
请问您训练模型时是用多少张卡(什么卡)跑的？

**Comment by Aldrich2y** [comment]
单卡。如果条件允许，你可以设置batch size等于8，效果可能会更好。
