### ISSUE TITLE
coco config

### ISSUE THREAD

**Issue by liconghui12** [Aldrich2y/MIANet#7]
hello,is the training image size the same for COCO dataset as for PASCAL,Could you provide the configuration file for COCO?

**Comment by yanliu-1210** [comment]
您好，打扰一下，请问您该问题如何解决的？我尝试在COCO数据集上训练时，一直出现数组索引越界问题，也即class_chosen变量出现问题，想问一下您这边对于COCO数据集是如何解决配置问题的

**Comment by liconghui12** [comment]
你好，修改一下mianet.py中的embedding,改为embeddings/word2vec_coco应该可以

**Comment by yanliu-1210** [comment]
谢谢谢谢谢谢谢谢谢谢！！！！！！谢谢你！！！

**Comment by yanliu-1210** [comment]
您好，再次打扰您，请问一下您在5-shot上训练测试是否达到了预期的指标，我这边在5-shot复现出现的差异过大，可以麻烦问一下配置文件是否有哪些需要更改的地方？谢谢您

**Comment by liconghui12** [comment]
不好意思帮不到你了，我没有跑这篇论文5-shot的实验。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Aldrich2y/MIANet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月13日(星期三) 上午10:36
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Aldrich2y/MIANet] coco config (Issue #7)





 
您好，再次打扰您，请问一下您在5-shot上训练测试是否达到了预期的指标，我这边在5-shot复现出现的差异过大，可以麻烦问一下配置文件是否有哪些需要更改的地方？谢谢您
